package com.pies.api.projeto.integrado.pies_backend.controller.dto;

public record CreateDiagnosticoInicialDTO(

        Boolean falaSeuNome,
        Boolean dizDataNascimento,
        Boolean lePalavras,
        Boolean informaNumeroTelefone,
        Boolean emiteRespostas,
        Boolean transmiteRecado,
        Boolean informaEndereco,
        Boolean informaNomePais,
        Boolean compreendeOrdens,
        Boolean expoeIdeias,
        Boolean recontaHistorias,
        Boolean usaSistemaCA,
        Boolean relataFatosComCoerencia,
        Boolean pronunciaLetrasAlfabeto,
        Boolean verbalizaMusicas,
        Boolean interpretaHistorias,
        Boolean formulaPerguntas,
        Boolean utilizaGestosParaSeComunicar,

        Boolean demonstraCooperacao,
        Boolean timidoInseguro,
        Boolean fazBirra,
        Boolean solicitaOfereceAjuda,
        Boolean riComFrequencia,
        Boolean compartilhaOQueESeu,
        Boolean demonstraAmorGentilezaAtencao,
        Boolean choraComFrequencia,
        Boolean interageComColegas,

        Boolean captaDetalhesGravura,
        Boolean reconheceVozes,
        Boolean reconheceCancoes,
        Boolean percebeTexturas,
        Boolean percepcaoCores,
        Boolean discriminaSons,
        Boolean discriminaOdores,
        Boolean aceitaDiferentesTexturas,
        Boolean percepcaoFormas,
        Boolean identificaDirecaoSom,
        Boolean percebeDiscriminaSabores,
        Boolean acompanhaFocoLuminoso,

        Boolean movimentoPincaComTesoura,
        Boolean amassaPapel,
        Boolean caiComFacilidade,
        Boolean encaixaPecas,
        Boolean recorta,
        Boolean unePontos,
        Boolean consegueCorrer,
        Boolean empilha,
        Boolean agitacaoMotora,
        Boolean andaLinhaReta,
        Boolean sobeDesceEscadas,
        Boolean arremessaBola,

        Boolean usaSanitarioSemAjuda,
        Boolean penteiaSeSo,
        Boolean consegueVestirDespirSe,
        Boolean lavaSecaAsMaos,
        Boolean banhoComModeracao,
        Boolean calcaSeSo,
        Boolean reconheceRoupas,
        Boolean abreFechaTorneira,
        Boolean escovaDentesSemAjuda,
        Boolean consegueDarNosLacos,
        Boolean abotoaDesabotoaRoupas,
        Boolean identificaPartesDoCorpo,

        Boolean garatujas,
        Boolean preSilabico,
        Boolean silabico,
        Boolean silabicoAlfabetico,
        Boolean alfabetico,

        String observacoes
) {}
